# Generated by Django 5.0 on 2024-08-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_alter_comment_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profileimage',
            field=models.ImageField(default='blank.png', upload_to='post_profileImage'),
        ),
    ]
