# Generated by Django 5.0 on 2024-08-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
