# Generated by Django 5.0 on 2024-08-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_level_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
