# Generated by Django 5.0 on 2024-09-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_delete_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.FileField(null=True, upload_to='Chat_Image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.FileField(null=True, upload_to='Video_Image'),
        ),
    ]
