# Generated by Django 5.0 on 2024-09-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_comment_image_comment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.FileField(null=True, upload_to='Chat_Image'),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(null=True, upload_to='Video_Image'),
        ),
    ]
