# Generated by Django 5.0 on 2024-09-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_remove_message_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.FileField(null=True, upload_to='Image'),
        ),
    ]
