# Generated by Django 5.0 on 2024-09-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0044_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(null=True, upload_to='Image'),
        ),
    ]
