# Generated by Django 5.0 on 2024-10-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_message_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.CharField(max_length=525)),
                ('image', models.FileField(max_length=255, upload_to='announcement')),
                ('video', models.FileField(max_length=255, upload_to='announcement')),
            ],
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='LastMessage',
        ),
    ]
