# Generated by Django 5.0 on 2024-10-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0047_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
