# Generated by Django 5.0 on 2024-10-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0048_chat_last_message_chat_last_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.CharField(default='No Messeges', max_length=255),
        ),
    ]
