# Generated by Django 5.0 on 2024-10-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0049_alter_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user_profile_img',
            field=models.FileField(default='blank.png', upload_to='Chat Image'),
        ),
    ]
