# Generated by Django 5.0 on 2024-10-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0050_chat_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='follower_profile_img',
            field=models.FileField(default='blank.png', upload_to='Chat Image'),
        ),
        migrations.AddField(
            model_name='chat',
            name='id_follower',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='id_user',
            field=models.IntegerField(null=True),
        ),
    ]
